/* generated by MCS-Assembler tool ASM-MCS version 0.5 */
/* Copyright (C) 2011-2013 by Robert Bosch GmbH, Germany */
/* target architecture : mcs24-1 */

#ifndef MCS_DEFS_H_
#define MCS_DEFS_H_

#define OFFSET_MCS0_MEM     (   0) /* byte address offset for assembled code in array C-arry 'mcs0_mem' */
#define SIZE_MCS0_MEM       ( 692) /* code size in bytes of assembled code in C-array 'mcs0_mem' */

#define LABEL_MCS0_MEM_TSK0_DONE                 ( 172) /* Index into C-array 'mcs0_mem' for assembler label 'TSK0_DONE' */
#define LABEL_MCS0_MEM_ACH5_SR0                  ( 136) /* Index into C-array 'mcs0_mem' for assembler label 'ACH5_SR0' */
#define LABEL_MCS0_MEM_TSK0_STACK                (   8) /* Index into C-array 'mcs0_mem' for assembler label 'TSK0_STACK' */
#define LABEL_MCS0_MEM_ACH3_SR0                  ( 132) /* Index into C-array 'mcs0_mem' for assembler label 'ACH3_SR0' */
#define LABEL_MCS0_MEM_ACH2_SR1                  ( 131) /* Index into C-array 'mcs0_mem' for assembler label 'ACH2_SR1' */
#define LABEL_MCS0_MEM_TI10_GP1                  ( 105) /* Index into C-array 'mcs0_mem' for assembler label 'TI10_GP1' */
#define LABEL_MCS0_MEM_ACH2_SR0                  ( 130) /* Index into C-array 'mcs0_mem' for assembler label 'ACH2_SR0' */
#define LABEL_MCS0_MEM_TSK0_LOOP                 ( 143) /* Index into C-array 'mcs0_mem' for assembler label 'TSK0_LOOP' */
#define LABEL_MCS0_MEM_TI10_GP0                  ( 104) /* Index into C-array 'mcs0_mem' for assembler label 'TI10_GP0' */
#define LABEL_MCS0_MEM_ACH3_SR1                  ( 133) /* Index into C-array 'mcs0_mem' for assembler label 'ACH3_SR1' */
#define LABEL_MCS0_MEM_ACH7_SR0                  ( 140) /* Index into C-array 'mcs0_mem' for assembler label 'ACH7_SR0' */
#define LABEL_MCS0_MEM_ACH1_SR0                  ( 128) /* Index into C-array 'mcs0_mem' for assembler label 'ACH1_SR0' */
#define LABEL_MCS0_MEM_ACH7_SR1                  ( 141) /* Index into C-array 'mcs0_mem' for assembler label 'ACH7_SR1' */
#define LABEL_MCS0_MEM_TI11_GP0                  ( 106) /* Index into C-array 'mcs0_mem' for assembler label 'TI11_GP0' */
#define LABEL_MCS0_MEM_TI11_GP1                  ( 107) /* Index into C-array 'mcs0_mem' for assembler label 'TI11_GP1' */
#define LABEL_MCS0_MEM_ACH1_SR1                  ( 129) /* Index into C-array 'mcs0_mem' for assembler label 'ACH1_SR1' */
#define LABEL_MCS0_MEM_ACH4_SR0                  ( 134) /* Index into C-array 'mcs0_mem' for assembler label 'ACH4_SR0' */
#define LABEL_MCS0_MEM_ACH4_SR1                  ( 135) /* Index into C-array 'mcs0_mem' for assembler label 'ACH4_SR1' */
#define LABEL_MCS0_MEM_ACH5_SR1                  ( 137) /* Index into C-array 'mcs0_mem' for assembler label 'ACH5_SR1' */
#define LABEL_MCS0_MEM_ACH6_SR0                  ( 138) /* Index into C-array 'mcs0_mem' for assembler label 'ACH6_SR0' */
#define LABEL_MCS0_MEM_ACH6_SR1                  ( 139) /* Index into C-array 'mcs0_mem' for assembler label 'ACH6_SR1' */
#define LABEL_MCS0_MEM_TSK0_INIT                 ( 142) /* Index into C-array 'mcs0_mem' for assembler label 'TSK0_INIT' */

#endif
