// -----------------------------------------------------------------------------
// Copyright (C) Australian Semiconductor Technology Company (ASTC). 2013.
// All Rights Reserved.
//
// This is unpublished proprietary source code of the Australian Semiconductor
// Technology Company (ASTC).  The copyright notice does not evidence any actual
// or intended publication of such source code.
// -----------------------------------------------------------------------------


#define USE_MCS
//#undef  USE_MCS

#include <stdio.h>
#include <math.h>
#include "gtm.h"

#include "global.h"
//#include "rh850_irq.h"
//#include "icu_feret.h"

#include "mcs_defs.h" // definition of MCS0_RAM label
#include "mcs_RAM.h" // data array generated by assembler

int init_int(void);
void gtm_start(void);

// calculate sinus factor
double sin_fact1;
double sin_fact2;
double sin_fact3;
volatile int nr_of_calls=2;

//MCS_RAM
#define MCS0_MEM_BASE 0xFFE38000

#ifdef USE_MCS
#define MCS0_WRADDR0  0x077
#define MCS0_WRADDR1  0x078
#define MCS0_WRADDR2  0x079
#define MCS0_WRADDR3  0x07A
#define MCS0_WRADDR4  0x07B
#define MCS0_WRADDR5  0x07C
#define MCS0_WRADDR6  0x07D
#define MCS0_WRADDR7  0x07E
#define MCS0_WRADDR8  0x07F
#define MCS0_WRADDR9  0x080
#define MCS0_WRADDR10 0x081
#define MCS0_WRADDR11 0x082
#define MCS0_WRADDR12 0x083
#define MCS0_WRADDR13 0x084
#define MCS0_WRADDR14 0x085
#define MCS0_WRADDR15 0x086
#define MCS0_WRADDR16 0x087
#define MCS0_WRADDR17 0x088
#define MCS0_WRADDR18 0x089
#define MCS0_WRADDR19 0x08A
#define MCS0_WRADDR20 0x08B
#define MCS0_WRADDR21 0x08C
#define MCS0_WRADDR22 0x08D
#define MCS0_WRADDR23 0x08E
#endif

int init_int()
{
   // Interrupt controller configuration. PSW.EBV=1
   /*__asm("stsr 0x5, r10");
   __asm("mov 0x10000, r11");
   __asm("or r11, r10");
   __asm("ldsr r10, 5");*/


#ifdef USE_MCS
   EIC159  = 0x0041;//INTGTM_ATOM0_7
   EIBD159 = 0x00000001;
#else
   EIC159  = 0x0041;//INTGTM_ATOM0_7
   EIBD159 = 0x00000001;
   EIC145   = 0x0041;//INTGTM_TIM1_1 //GTM01I1 is connected to GTM0AT0O1
   EIBD145  = 0x00000001;
#endif
    
   // set 0x1000 to INTBP
  /* __asm("mov 0x1000, r10");
   __asm("ldsr r10, 4, 1");

   // set 1 to PSW.EBV
   __asm("stsr 5, r10");
   __asm("mov 0x8000, r11");
   __asm("or r11, r10");
   __asm("ldsr r10, 5");

   // set 0x0 to EBASE.EBASE
   __asm("mov 0x0, r10");
   __asm("ldsr r10, 3, 1");*/

    return 0;
}

void gtm_test()
{
  unsigned int status=0; 
#ifdef USE_MCS
  int *p;
  int i;
#endif
  
  // Configure INTC
  init_int();

  sin_fact1 = sin(((1*10)%360)*PI/180);
  sin_fact2 = sin(((1*10+120)%360)*PI/180);
  sin_fact3 = sin(((1*10+240)%360)*PI/180);

#ifdef USE_MCS
  printf("Initialize MCS RAM\n");
  status = GTM0.MCS0CTRLSTAT; // get current status
  if ((status & 0x00010000) > 0) { // wait until MCS RAM intitialization finished
    do {
      status = GTM0.MCS0CTRLSTAT;
    } while ((status & 0x00010000) > 0);
  }
  printf("Copy MCS program code to RAM\n");
  p = (int *)MCS0_MEM_BASE; // pointer to first entry of MCS0 RAM
  for (i=0; i<(SIZE_MCS0_MEM/4); i++) {
    p[i] = mcs0_mem[i]; // store value to MCS RAM
  }

  printf("Store initial duty cycle and period values to MCS RAM\n");
  p[ LABEL_MCS0_MEM_ACH1_SR0] = (T0/2)-(T0/4+(int)(sin_fact1*((T0/4)-10)));
  p[ LABEL_MCS0_MEM_ACH1_SR1] = (T0/2)+(T0/4+(int)(sin_fact1*((T0/4)-10)));
  p[ LABEL_MCS0_MEM_ACH2_SR0] = (T0/2)-(T0/4+(int)(sin_fact1*((T0/4)-10)));
  p[ LABEL_MCS0_MEM_ACH2_SR1] = (T0/2)+(T0/4+(int)(sin_fact1*((T0/4)-10)));
  p[ LABEL_MCS0_MEM_ACH3_SR0] = (T0/2)-(T0/4+(int)(sin_fact2*((T0/4)-10)));
  p[ LABEL_MCS0_MEM_ACH3_SR1] = (T0/2)+(T0/4+(int)(sin_fact2*((T0/4)-10)));
  p[ LABEL_MCS0_MEM_ACH4_SR0] = (T0/2)-(T0/4+(int)(sin_fact2*((T0/4)-10)));
  p[ LABEL_MCS0_MEM_ACH4_SR1] = (T0/2)+(T0/4+(int)(sin_fact2*((T0/4)-10)));
  p[ LABEL_MCS0_MEM_ACH5_SR0] = (T0/2)-(T0/4+(int)(sin_fact3*((T0/4)-10)));
  p[ LABEL_MCS0_MEM_ACH5_SR1] = (T0/2)+(T0/4+(int)(sin_fact3*((T0/4)-10)));
  p[ LABEL_MCS0_MEM_ACH6_SR0] = (T0/2)-(T0/4+(int)(sin_fact3*((T0/4)-10)));
  p[ LABEL_MCS0_MEM_ACH6_SR1] = (T0/2)+(T0/4+(int)(sin_fact3*((T0/4)-10)));
  p[ LABEL_MCS0_MEM_ACH7_SR0] = (2*T0);
  p[ LABEL_MCS0_MEM_ACH7_SR1] = CH7_Pulse_length;
  GTM0.MCS00CTRL = 0x00000001; // enable MCS channel 0
  GTM0.ATOM01RDADDR = (MCS0_WRADDR0<<16)+(MCS0_WRADDR0); // read from MCS WR_ADDR0
  GTM0.ATOM02RDADDR = (MCS0_WRADDR1<<16)+(MCS0_WRADDR1);
  GTM0.ATOM03RDADDR = (MCS0_WRADDR2<<16)+(MCS0_WRADDR2);
  GTM0.ATOM04RDADDR = (MCS0_WRADDR3<<16)+(MCS0_WRADDR3);
  GTM0.ATOM05RDADDR = (MCS0_WRADDR4<<16)+(MCS0_WRADDR4);
  GTM0.ATOM06RDADDR = (MCS0_WRADDR5<<16)+(MCS0_WRADDR5);
  GTM0.ATOM07RDADDR = (MCS0_WRADDR6<<16)+(MCS0_WRADDR6); // read from MCS WR_ADDR6
#endif

  printf ("Configure CMU\n");
  GTM0.CMUGCLKNUM  = 0x0000FFFF; // global divider = *1
  GTM0.CMUGCLKDEN  = 0x0000FFFF;
  GTM0.CMUCLK3CTRL = 0x00000004; // sys_clk_period *5 = 62,5ns @ 80MH sys_clk
  GTM0.CMUCLKEN    = 0x00000080; // enable CMU clock 3
  status = GTM0.CMUCLKEN;
  if (status != 0x000000C0) {
    printf("ERROR: CMU clock 3 cannot be enabled\n");
    while(1);//Stay here if clock could not be enabled
  }

  printf ("Configure TIM\n");
#ifdef USE_MCS
  GTM0.TIM10CTRL   = 0x03002F21;//0x03002F21 to measure GTM0AT0O0, ARU enabled
  GTM0.TIM11CTRL   = 0x03002F21;//to measure GTM0AT0O1, ARU enabled
  //GTM0TIM11IRQEN  = 0x00000001;//enable NEWVAL IRQ
#else
  GTM0.TIM10CTRL   = 0x03002F01;//to measure GTM0AT0O0
  GTM0.TIM11CTRL   = 0x03002F01;//to measure GTM0AT0O1
  GTM0.TIM11IRQEN  = 0x00000001;//enable NEWVAL IRQ
#endif


  printf("Configure DTM24 (connected to outputs of ATOM0 channel 0 to 3)\n");
  GTM0.DTM24CHCTRL2 = 0x88888800; // enable dead time channel 1,2,3
  GTM0.DTM241DTV    = 0x00640064; // RELRISE=100, RELFALL=100 @sys_clk = 1,25µs
  GTM0.DTM242DTV    = 0x00640064; // RELRISE=100, RELFALL=100
  GTM0.DTM243DTV    = 0x00640064; // RELRISE=100, RELFALL=100
  
#ifdef USE_MCS
  printf("Channel 0 is master channel that defines period of PWM\n");
  GTM0.ATOM00CTRL = (mode_somp)+(sl_hi)+(trig_ccu0)+(cmu_clk3);
  printf("Channel 1 to 6 are synchronized to channel 1 and middle symmetrical\n");
  GTM0.ATOM01CTRL = (mode_somp)+(aru_on)+(sl_hi)+(rst_on_trig)+(cmu_clk3);
  GTM0.ATOM02CTRL = (mode_somp)+(aru_on)+(sl_lo)+(rst_on_trig)+(cmu_clk3);
  GTM0.ATOM03CTRL = (mode_somp)+(aru_on)+(sl_hi)+(rst_on_trig)+(cmu_clk3);
  GTM0.ATOM04CTRL = (mode_somp)+(aru_on)+(sl_lo)+(rst_on_trig)+(cmu_clk3);
  GTM0.ATOM05CTRL = (mode_somp)+(aru_on)+(sl_hi)+(rst_on_trig)+(cmu_clk3);
  GTM0.ATOM06CTRL = (mode_somp)+(aru_on)+(sl_lo)+(rst_on_trig)+(cmu_clk3);
  printf("Channel 7 triggers reload of SRx register\n");
  GTM0.ATOM07CTRL = (mode_somp)+(aru_on)+(sl_hi)+(cmu_clk3)+(trig_ccu0);
#else 
  printf("Channel 0 is master channel that defines period of PWM\n");
  GTM0.ATOM00CTRL = (mode_somp)+(sl_hi)+(trig_ccu0)+(cmu_clk3);
  printf("Channel 1 to 6 are synchronized to channel 1 and middle symmetrical\n");
  GTM0.ATOM01CTRL = (mode_somp)+(aru_off)+(sl_hi)+(rst_on_trig)+(cmu_clk3);
  GTM0.ATOM02CTRL = (mode_somp)+(aru_off)+(sl_lo)+(rst_on_trig)+(cmu_clk3);
  GTM0.ATOM03CTRL = (mode_somp)+(aru_off)+(sl_hi)+(rst_on_trig)+(cmu_clk3);
  GTM0.ATOM04CTRL = (mode_somp)+(aru_off)+(sl_lo)+(rst_on_trig)+(cmu_clk3);
  GTM0.ATOM05CTRL = (mode_somp)+(aru_off)+(sl_hi)+(rst_on_trig)+(cmu_clk3);
  GTM0.ATOM06CTRL = (mode_somp)+(aru_off)+(sl_lo)+(rst_on_trig)+(cmu_clk3);
  printf("Channel 7 triggers reload of SRx register\n");
  GTM0.ATOM07CTRL = (mode_somp)+(aru_off)+(sl_hi)+(cmu_clk3)+(trig_ccu0);
#endif

  // initial values for ATOM0 channel 0:
  GTM0.ATOM00CM0 = T0; // period = 1000*62,5ns = 16kHz
  GTM0.ATOM00CM1 = T0/2; // duty cycle = 500*62,5ns
  GTM0.ATOM00CN0 = 0x00000000; // initial delay = 0
  GTM0.ATOM00SR0 = T0;
  GTM0.ATOM00SR1 = T0/2;

  // initial value for ATOM0 channel 7:
  GTM0.ATOM07CM1 = CH7_Pulse_length; // falling edge if ATOM0_CH0_CN0=CH7_Pulse_length
  GTM0.ATOM07CM0 = 2*T0; // rising edge if ATOM0_CH0_CN0=2*T0
  GTM0.ATOM07SR1 = CH7_Pulse_length;
  GTM0.ATOM07SR0 = 2*T0;
  GTM0.ATOM07IRQEN     = 0x00000001; // enable interrupt CCU0 of ATOM0_CH7
  GTM0.ATOM0AGCINTTRIG = 0x00008000; // int. trig channel 7
  GTM0.ATOM0AGCGLBCTRL = 0x00020000; // update enable of ch 0
  // for motor control outputs 1 to 6 are used
  // for demonstration, enable output of channel 0 to 7
  GTM0.ATOM0AGCOUTENCTRL = 0x0000AAAA; // enable output 0 to 7 (1 to 6)
  GTM0.ATOM0AGCENDISCTRL = 0x0000AAAA; // anable all channel
  GTM0.ATOM0AGCFUPDCTRL  = 0xAAAAAAAA; // force update on ch 0 to 7
  GTM0.ATOM0AGCGLBCTRL   = 0x00000001; // host trigger for start of ATOM0

  //after enable by host trigger set force update flags for next internal trigger
  GTM0.ATOM0AGCFUPDCTRL  = 0xAAA9AAA9; // force update on ch 1 to 7
}

#pragma interrupt INTGTM_ATOM0_7(enable=false, channel=159, fpu=true, callt=false)
 void INTGTM_ATOM0_7(void)
{
#ifdef USE_MCS
  int *p;
  int gpr0, gpr1;
#endif
  
  printf("INTGTM_ATOM0_7 Interrupt Raised\n");
  
  GTM0.ATOM07IRQNOTIFY = 0x00000003; // reset NOTIFY flags

  // calculate sinus factor
  sin_fact1 = sin(((nr_of_calls*10)%360)*PI/180);
  sin_fact2 = sin(((nr_of_calls*10+120)%360)*PI/180);
  sin_fact3 = sin(((nr_of_calls*10+240)%360)*PI/180);
  nr_of_calls++;
  
#ifdef USE_MCS
  p = (int *)MCS0_MEM_BASE; // pointer to first entry of MCS0 RAM
  gpr0 = p[LABEL_MCS0_MEM_TI10_GP0];
  gpr1 = p[LABEL_MCS0_MEM_TI10_GP1];  
  printf("Measured ATOM0O0 PWM duty is equal to %i, and PWM period to %i\n",gpr0&0x0000FFFF, gpr1&0x0000FFFF);
  gpr0 = p[LABEL_MCS0_MEM_TI11_GP0];
  gpr1 = p[LABEL_MCS0_MEM_TI11_GP1];  
  printf("Measured ATOM0O1 PWM duty is equal to %i, and PWM period to %i\n",gpr0&0x0000FFFF, gpr1&0x0000FFFF);
  
  p[ LABEL_MCS0_MEM_ACH1_SR0] = (T0/2)-(T0/4+(int)(sin_fact1*((T0/4)-10)));
  p[ LABEL_MCS0_MEM_ACH1_SR1] = (T0/2)+(T0/4+(int)(sin_fact1*((T0/4)-10)));
  p[ LABEL_MCS0_MEM_ACH2_SR0] = (T0/2)-(T0/4+(int)(sin_fact1*((T0/4)-10)));
  p[ LABEL_MCS0_MEM_ACH2_SR1] = (T0/2)+(T0/4+(int)(sin_fact1*((T0/4)-10)));
  p[ LABEL_MCS0_MEM_ACH3_SR0] = (T0/2)-(T0/4+(int)(sin_fact2*((T0/4)-10)));
  p[ LABEL_MCS0_MEM_ACH3_SR1] = (T0/2)+(T0/4+(int)(sin_fact2*((T0/4)-10)));
  p[ LABEL_MCS0_MEM_ACH4_SR0] = (T0/2)-(T0/4+(int)(sin_fact2*((T0/4)-10)));
  p[ LABEL_MCS0_MEM_ACH4_SR1] = (T0/2)+(T0/4+(int)(sin_fact2*((T0/4)-10)));
  p[ LABEL_MCS0_MEM_ACH5_SR0] = (T0/2)-(T0/4+(int)(sin_fact3*((T0/4)-10)));
  p[ LABEL_MCS0_MEM_ACH5_SR1] = (T0/2)+(T0/4+(int)(sin_fact3*((T0/4)-10)));
  p[ LABEL_MCS0_MEM_ACH6_SR0] = (T0/2)-(T0/4+(int)(sin_fact3*((T0/4)-10)));
  p[ LABEL_MCS0_MEM_ACH6_SR1] = (T0/2)+(T0/4+(int)(sin_fact3*((T0/4)-10)));
  // trigger update by MCS:
  GTM0.MCS0STRG = 0x00000001; //set bit TRG0
#else
  GTM0.ATOM01SR0 = (T0/2)-(T0/4+(int)(sin_fact1*((T0/4)-10)));
  GTM0.ATOM01SR1 = (T0/2)+(T0/4+(int)(sin_fact1*((T0/4)-10)));
  GTM0.ATOM02SR0 = (T0/2)-(T0/4+(int)(sin_fact1*((T0/4)-10)));
  GTM0.ATOM02SR1 = (T0/2)+(T0/4+(int)(sin_fact1*((T0/4)-10)));
  GTM0.ATOM03SR0 = (T0/2)-(T0/4+(int)(sin_fact2*((T0/4)-10)));
  GTM0.ATOM03SR1 = (T0/2)+(T0/4+(int)(sin_fact2*((T0/4)-10)));
  GTM0.ATOM04SR0 = (T0/2)-(T0/4+(int)(sin_fact2*((T0/4)-10)));
  GTM0.ATOM04SR1 = (T0/2)+(T0/4+(int)(sin_fact2*((T0/4)-10)));
  GTM0.ATOM05SR0 = (T0/2)-(T0/4+(int)(sin_fact3*((T0/4)-10)));
  GTM0.ATOM05SR1 = (T0/2)+(T0/4+(int)(sin_fact3*((T0/4)-10)));
  GTM0.ATOM06SR0 = (T0/2)-(T0/4+(int)(sin_fact3*((T0/4)-10)));
  GTM0.ATOM06SR1 = (T0/2)+(T0/4+(int)(sin_fact3*((T0/4)-10)));
#endif

}

#pragma interrupt INTGTM_TIM1_1(enable=false, channel=145, fpu=true, callt=false)
void INTGTM_TIM1_1(void)
{
  printf("INTGTM_TIM1_1 Interrupt Raised\n");
  printf("Measured ATOM0O0 PWM duty is equal to %i, and PWM period to %i\n",GTM0.TIM10GPR0&0x0000FFFF, GTM0.TIM10GPR1&0x0000FFFF);
  printf("Measured ATOM0O1 PWM duty is equal to %i, and PWM period to %i\n",GTM0.TIM11GPR0&0x0000FFFF, GTM0.TIM11GPR1&0x0000FFFF);
  GTM0.TIM11IRQNOTIFY = 0x00000001;//clear the NEWVAL flag
}
